name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./chatbox  # Update this path to your desired directory

      - name: Lint and Build
        run: |
          pnpm run lint && pnpm run build
        working-directory: ./chatbox  # Update this path to your desired directory